name: Processador de Planilhas
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  processar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar dependências
        run: pip install pandas openpyxl
      - name: Executar processamento
        run: python processar_planilhas.py
      - name: Salvar resultados
        uses: actions/upload-artifact@v3
        with:
          name: planilhas-processadas
          path: resultados/
